# Generated by Django 4.1.6 on 2023-02-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(to='app.speaker'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(to='app.sponsor'),
        ),
    ]
