# Generated by Django 4.1.6 on 2023-02-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact_alter_event_speakers_alter_event_sponsors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
