# Generated by Django 4.1.6 on 2023-02-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sponsor_sponsor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('counter', models.IntegerField()),
            ],
        ),
    ]
