# Generated by Django 4.1.6 on 2023-02-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_counteritems'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='counters',
            field=models.ManyToManyField(related_name='counters', to='app.counteritems'),
        ),
    ]
