# Generated by Django 4.1.6 on 2023-02-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_event_counters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='counters',
        ),
        migrations.AddField(
            model_name='counteritems',
            name='Event',
            field=models.ManyToManyField(related_name='Event', to='app.event'),
        ),
    ]
