# Generated by Django 4.1.6 on 2023-02-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_counteritems_event_counteritems_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counteritems',
            name='Event',
        ),
        migrations.AddField(
            model_name='counteritems',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='app.event'),
        ),
    ]
