# Generated by Django 4.1.6 on 2023-02-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_counteritems_event_counteritems_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterItems',
        ),
    ]
