# Generated by Django 4.1.6 on 2023-02-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_eventregisterform'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisterform',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
        migrations.CreateModel(
            name='PAYMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.CharField(max_length=255)),
                ('session_id', models.TextField()),
                ('stripe_payment_intent', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Completed', 'Completed'), ('Purchased', 'Purchased'), ('Cancel', 'Cancel')], max_length=255)),
                ('eventregister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.eventregisterform')),
            ],
        ),
    ]
