# Generated by Django 4.1.6 on 2023-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_eventregisterform_event_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisterform',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
