# Generated by Django 4.1.6 on 2023-02-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_eventregisterform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregisterform',
            name='number_of_persons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
