# Generated by Django 4.1.6 on 2023-03-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_eventregisterform_number_of_persons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Event Items Counter'},
        ),
        migrations.AddField(
            model_name='items',
            name='use_in_home_page',
            field=models.BooleanField(default=True),
        ),
    ]
