# Generated by Django 4.1.6 on 2023-03-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_items_options_items_use_in_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='use_in_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
